### ISSUE TITLE
import RPi.GPIO as GPIO

### ISSUE THREAD

**Issue by gc-robotics** [mlherd/ros2_pi_gpio#2]
how does python-rpi.gpio get installed? 
It is not amongst the rosdep-managed dependencies. 
Is your assumption that the package requires to be preinstalled? 

Thanks.

**Comment by mlherd** [comment]
Have you tried `sudo apt install python-rpi.gpio`?

**Comment by mlherd** [comment]
I am closing this issue since there has been no response. Please feel free to reopen it if you still have the problem.
